app/urls.py
from django.urls import  path
from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('scan/<int:pk>/', scan, name='scan'),
    path('targets_scan/', targets_scan, name='targets_scan'),
    path('compare_scans/<int:pk>/', compare_scans, name='compare_scans'),
    path('discard_scans/<int:pk>/', discard_scans, name='discard_scans'),
    path('vulnerabilities/<int:pk>/', vulnerabilities, name='vulnerabilities'),
    path('details/<int:pk>/', details, name='details'),
    path('<slug:slug>/employees/<int:pk>/', employees, name='employees'),
    path('employees_emails_scan/<int:pk>/', employees_emails_scan, name='employees_emails_scan'),
    path('update_target/<int:pk>/', update_target, name='update_target'),
    path('target_delete/<int:pk>/', target_delete, name='target_delete'),
    path('targets/', targets, name='targets'),
    path('vulnerability_scan/', vulnerability_scan, name='vulnerability_scan'),
    path('scan/',scans, name='scan'),
    path('<task_id>/', get_progress, name='task_status'),
    path('<task_id>/cancel_scan', cancel_scan, name='cancel_scan'),

   
    # path('add_target/',add_target, name='add_target'),


    # path('get-task-info/', get_task_info),
    # path('generate-user/', generate_random_user),

    #path('scantarget/', scantarget, name='scantarget'),


    
    

      ]

emc/urls.py
from django.urls import  path
from .views import *

urlpatterns = [
    
    path('', emc, name='emc'),
    path('search/', EMCTargetListView.as_view(), name='search'),
    path('target/<int:pk>/<slug:slug>/',EMCTargetDetailView.as_view(), name='target-emc'),
   
      ]

scot/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from app.views import index
from allauth.account import views as allauthviews
urlpatterns = [
    re_path(r'^$', allauthviews.login),
    path('scot/kiongozi/', admin.site.urls),
    path('app/', include('app.urls')),
    path('emc/', include('emc.urls')),
    path('social/', include('socialengineering.urls')),
    path('weapons/', include('weapon.urls')),
    path('celery-progress/', include('celery_progress.urls')),
    path('accounts/', include('allauth.urls')),
    path('webpush/', include('webpush.urls')),
    path('api-auth/', include('rest_framework.urls')),
] +static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app/models.py
from djongo import models
from django.template.defaultfilters import slugify
from django.utils.http import is_safe_url
from django.db.models.signals import post_save
from django.dispatch import receiver


class Country(models.Model):
    country = models.CharField(max_length=200)
    def __str__(self):
        return self.country

class Category(models.Model):
    category = models.CharField(max_length=200)
    def __str__(self):
        return self.category
    class Meta:
        verbose_name = "Data Source"
        verbose_name_plural ="Data Sources"

class Target(models.Model):
    name = models.CharField(max_length = 300)
    target = models.CharField(max_length = 300, help_text="example.com")
    country     = models.ForeignKey(Country, on_delete=models.CASCADE, null=True,blank=True)
    category    = models.ForeignKey(Category, on_delete = models.CASCADE, null=True, blank=True, verbose_name='Data Source')
    
    ip = models.CharField(max_length = 300)
   
    # domain = models.CharField(max_length = 300, verbose_name ="Target Domain")
    status = models.CharField(max_length = 300)
    slug=models.SlugField(unique=True, null=True,blank=True)
    def save(self,*args,**kwargs):
        self.slug=slugify(self.target)
        super(Target, self).save(*args,**kwargs)

    def __str__(self):
        return self.target

# @receiver(post_save, sender=Target, dispatch_uid="create_target_status_tracking_instance")
# def post_save(sender, instance, **kwargs):
#      instance.targetspingtrack = instance
#      instance.targetspingtrack.ip = instance.ip
#      instance.targetspingtrack.status = instance.status
#      instance.targetspingtrack.save()



class Employee(models.Model):
    company = models.ForeignKey(Target,on_delete=models.CASCADE, verbose_name="Target Company")
    name = models.CharField(max_length=300)
    linked_url = models.CharField(max_length=500, null=True, blank=True)

    def __str__(self):
        return self.name

class TargetsPingTrack(models.Model):
    target = models.ForeignKey(Target, on_delete=models.CASCADE)
    ip = models.CharField(max_length=200)
    status = models.CharField(max_length=200)
    date = models.DateTimeField(auto_now_add=True)
    def  __str__(self):
        return self.target.target

class Whois(models.Model):
    target = models.ForeignKey(Target,on_delete=models.CASCADE)
    ip = models.CharField(max_length=500)
    sh_domain =  models.CharField(max_length=500)
    city =  models.CharField(max_length=500)
    country =  models.CharField(max_length=500)
    description =  models.CharField(max_length=500)

    asn = models.CharField(max_length=500)
    asn_cidr = models.CharField(max_length=500)
    asn_registry = models.CharField(max_length=500)
    status =  models.CharField(max_length=500)


    emails =  models.CharField(max_length=500)
    name =  models.CharField(max_length=500)
    ip_range =  models.CharField(max_length=500)
    state = models.CharField(max_length=500)
    server_info = models.CharField(max_length=500)
    registrar = models.CharField(max_length=500)
    owner = models.CharField(max_length=500)
    owner_city = models.CharField(max_length=500)
    owner_state = models.CharField(max_length=500)
    owner_country =models.CharField(max_length=500)
    owner_company =models.CharField(max_length=500)
    domain_emails = models.CharField(max_length=500)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.target.target

    

class domain_dnsrecords_db(models.Model):
    target = models.ForeignKey(Target,on_delete=models.CASCADE)
    soa_records =   models.CharField(max_length=500)
    mx_records =    models.CharField(max_length=500)
    txt_records =   models.CharField(max_length=500)
    a_records =     models.CharField(max_length=500)
    name_server_records =  models.CharField(max_length=500)
    cname_records = models.CharField(max_length=500)
    aaaa_records =  models.CharField(max_length=500)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.target.target

class Service_provider(models.Model):
    isp = models.CharField(max_length=500)
    code = models.CharField(max_length=500)
    ip_adresses = models.CharField(max_length=500)
    def __str__(self):
        return self.isp
    
class Host(models.Model):
    target = models.ForeignKey(Target,on_delete=models.CASCADE)
    host = models.CharField(max_length=500)
    status = models.CharField(max_length=500)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.target.target

    

class Port(models.Model):
    target = models.ForeignKey(Target,on_delete=models.CASCADE)
    port = models.CharField(max_length=500)
    status = models.CharField(max_length=500)
    name = models.CharField(max_length=500)
    product = models.CharField(max_length=500)
    version = models.CharField(max_length=500)
    server_extrainfo = models.CharField(max_length=500)
    cpe = models.CharField(max_length=500)
    date = models.DateTimeField(auto_now_add=True)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.target.target

  

class Email_harvest_db(models.Model):
    target = models.ForeignKey(Target,on_delete=models.CASCADE)
    email_records = models.CharField(max_length=500)
    employee = models.ForeignKey(Employee,on_delete=models.CASCADE, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.target.target


class Web_app_info_db(models.Model):
    target = models.ForeignKey(Target,on_delete=models.CASCADE)
    key = models.CharField(max_length=500)
    app_info = models.CharField(max_length=500)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.target.target
  

class Virtual_Host_db(models.Model):
    ip = models.CharField(max_length=500)
    target = models.ForeignKey(Target,on_delete=models.CASCADE)
    main_domain = models.CharField(max_length=500)
    location = models.CharField(max_length=500)
    routedesc = models.CharField(max_length=500)
    asname = models.CharField(max_length=500)
    bgp_route = models.CharField(max_length=500)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.target.target

class Virtual_Host(models.Model):
    target = models.ForeignKey(Target,on_delete=models.CASCADE)
    v_hosts = models.CharField(max_length=500)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.target.target
    
    
class Web_search(models.Model):
    target = models.ForeignKey(Target,on_delete=models.CASCADE)
    title = models.CharField(max_length=500)
    desc = models.CharField(max_length=500)
    url = models.CharField(max_length=500)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.target.target


class Pagelinks(models.Model):
    target = models.ForeignKey(Target,on_delete=models.CASCADE)
    links = models.CharField(max_length=500)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.target.target


class Vulnerabilities(models.Model):
    target = models.ForeignKey(Target,on_delete=models.CASCADE)
    exploit =  models.CharField(max_length=500)
    web_vuln_tech = models.CharField(max_length=500)
    web_vuln_name = models.CharField(max_length=500)
    web_vuln_description = models.CharField(max_length=500)
    web_vuln_severity_class = models.CharField(max_length=500)
    web_vuln_ref = models.CharField(max_length=500)

class SysVulnerabilities(models.Model):
    target = models.ForeignKey(Target,on_delete=models.CASCADE)
    service_vuln_tech = models.CharField(max_length=500)
    vulnerability = models.CharField(max_length=500)
    vuln_description = models.CharField(max_length=500)
    severity = models.CharField(max_length=500)
    exploit =  models.CharField(max_length=500)
    cvss_score = models.CharField(max_length=500)

class Phone_Number(models.Model):
    target = models.ForeignKey(Target,on_delete=models.CASCADE)
    employee = models.ForeignKey(Employee,on_delete=models.CASCADE, null=True, blank=True)
    phone_number = models.CharField(max_length=500)
    
# class server_info(models.Model):
#     target = models.ForeignKey(Target,on_delete=models.CASCADE, default=1)
#     os_name = models.CharField(max_length=500)
#     os_vendor = models.CharField(max_length=500)
#     os_gen = models.CharField(max_length=500)


class WhoisStaging(models.Model):
    target = models.ForeignKey(Target,on_delete=models.CASCADE)
    ip = models.CharField(max_length=500)
    sh_domain =  models.CharField(max_length=500)
    city =  models.CharField(max_length=500)
    country =  models.CharField(max_length=500)
    description =  models.CharField(max_length=500)

    asn = models.CharField(max_length=500)
    asn_cidr = models.CharField(max_length=500)
    asn_registry = models.CharField(max_length=500)
    status =  models.CharField(max_length=500)


    emails =  models.CharField(max_length=500)
    name =  models.CharField(max_length=500)
    ip_range =  models.CharField(max_length=500)
    state = models.CharField(max_length=500)
    server_info = models.CharField(max_length=500)
    registrar = models.CharField(max_length=500)
    owner = models.CharField(max_length=500)
    owner_city = models.CharField(max_length=500)
    owner_state = models.CharField(max_length=500)
    owner_country =models.CharField(max_length=500)
    owner_company =models.CharField(max_length=500)
    domain_emails = models.CharField(max_length=500)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.target.target

    

class domain_dnsrecords_db_staging(models.Model):
    target = models.ForeignKey(Target,on_delete=models.CASCADE)
    soa_records =   models.CharField(max_length=500)

emc/models.py
from django.db import models

# Create your models here.

emc/views.py
from django.shortcuts import render
from django.contrib.messages import get_messages
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from app.models import Target, Email_harvest_db
from django.db.models import Q
@login_required
def emc(request):
	return render(request, 'emc/emc.html', {})



class EMCTargetListView(LoginRequiredMixin,ListView):
	template_name ="emc/emc.html"
	model = Target
	def get_queryset(self, *args, **kwargs):
		qs = Target.objects.all()
		query = self.request.GET.get("q", None)
		if query is not None:
			qs = qs.filter(
				Q(target__icontains=query) |
				Q(name__icontains=query))
		return qs
	context_object_name ='filtered_targets'


class EMCTargetDetailView(LoginRequiredMixin,DetailView):
	model =Target
	# context_object_name ='target'
	template_name ="emc/emc-target.html"
	def get_context_data(self, **kwargs):
		context = super(EMCTargetDetailView, self).get_context_data(**kwargs)
		context['emails'] = Email_harvest_db.objects.filter(target=self.get_object())
		return context



# class UserProfileDetailView(DetailView):
#     model = get_user_model()
#     slug_field = "username" 
#     template_name = "perfil.html"

#     def get_context_data(self, **kwargs):
#         # xxx will be available in the template as the related objects
#         context = super(UserProfileDetailView, self).get_context_data(**kwargs)
#         context['xxx'] = Email_harvest_db.objects.filter(target=self.get_object())
#         return context

templates/scot/add_target.html
				

							

						
                                   

						
								
								
								 <a href=".d_target" data-toggle="modal" class="btn btn-info btn-sm" style="float: right;"> Add this target to the List</a>
								 <div class="modal fade d_target " tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
									  <div class="modal-dialog" role="document">
									    <div class="modal-content">
									      <div class="modal-header">
									        <h5 class="modal-title" id="exampleModalLabel">Define a New Target</h5>
									        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
									          <span aria-hidden="true">&times;</span>
									        </button>
									      </div>
									      <div class="modal-body">
									        <form class="form-horizontal" method="post" action=".">
									        	{% csrf_token %}
									        	<fieldset>
													<div class="form-group has-info">
														<div class="col-md-10 col-md-offset-1">
															
															<div class="form-group has-info" style="text-align: left;">
																<label for="domain" class="control-label">Target Domain</label>
																<input type="text" class="form-control"  placeholder="e.g example.com" value="example.com" name="domain">
															</div>
																
															
															<div class="form-group has-info" style="text-align: left;">
																<label for="name" class="control-label">Target Name</label>
																<input type="text" class="form-control"  placeholder="e.g example LTD" name="name">
															</div>
															<div class="form-group has-info" style="text-align: left;">
																<label for="country" class="control-label">Target Country</label>
																<input type="text" class="form-control"  placeholder="e.g Kenya" name="country">
															</div>
															
																
															<div class="form-group has-info" style="text-align: left;">
																<label for="sector" class="control-label">Target Sector</label>
																<input type="text" class="form-control"  placeholder="e.g Energy" name="sector">
															</div>
														
										
																<input type="hidden" class="form-control" id="ip" name="ip" value="{{ip}}" placeholder="Energy Sector">
																<input type="hidden" class="form-control"  name="status" value="{{status}}" placeholder="Energy Sector">
															</div>
														</div>
													</fieldset>

									       
									       
									      </div>
									      <div class="modal-footer">
									        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
									        <button type="submit" value="btnform2" name= "btnform2" class="btn btn-info">Save Target</button>
									      </div>
											 </form>					
									    </div>
									  </div>
									</div>
								

templates/scot/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
	<head>
		
		{% include 'include/css.html' %}
	</head>

	<body>
		
		<!-- Header starts -->
		{% include 'include/header.html' %}
		<!-- Header ends -->

		<!-- Container fluid Starts -->
		<div class="container-fluid">

			<!-- Navbar starts -->
			{% include 'include/navbar.html' %}
			<!-- Navbar ends -->

			<!-- Dashboard wrapper starts -->
			<div class="dashboard-wrapper">

				<!-- Top bar starts -->
				{% block page_top_bar %}
				
				{% endblock %}

				<!-- Main container starts -->
				<div class="main-container">
					

					{% block content %}


					<!-- Row starts -->
					<div class="row gutter">
						
					</div>
					<!-- Row ends -->

					{% endblock %}
				</div>
				<!-- Main container ends -->
			
			</div>
			<!-- Dashboard Wrapper End -->
		</div>
		
		<!-- Container fluid ends -->

		<!-- Footer Start -->
		{% include 'include/footer.html' %}
		<!-- Footer end -->

		{% include 'include/js.html' %}




		{% block javasccript %}
		{% endblock %}
	
	</body>
</html>

templates/scot/emc.html
{% extends 'scot/base.html' %}

{% block page_top_bar %}
<!-- <style type="text/css">
    .nav-tabs { border-bottom: 2px solid #DDD; }
    .nav-tabs > li.active > a, .nav-tabs > li.active > a:focus, .nav-tabs > li.active > a:hover { border-width: 0; }
    .nav-tabs > li > a { border: none; color: #666; }
        .nav-tabs > li.active > a, .nav-tabs > li > a:hover { border: none; color: #4285F4 !important; background: transparent; }
        .nav-tabs > li > a::after { content: ""; background: #4285F4; height: 2px; position: absolute; width: 100%; left: 0px; bottom: -1px; transition: all 250ms ease 0s; transform: scale(0); }
    .nav-tabs > li.active > a::after, .nav-tabs > li:hover > a::after { transform: scale(1); }
.tab-nav > li > a::after { background: #21527d none repeat scroll 0% 0%; color: #fff; }
.tab-pane { padding: 15px 0; }
.tab-content{padding:20px}

</style> -->
              <div class="top-bar clearfix">
                    <div class="row gutter">
                        <div class="col-lg-3 col-md-3 col-sm- col-xs-12">
                            <div class="page-title" style="font-size: 9px;">
                                <h4> Exploit Management Center </h4>
                            </div>
                        </div>
                        <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
                            <ul class="nav nav-tabs" role="tablist">
                                
                                        <li role="presentation" ><a href="#whois" aria-controls="whois" role="tab" data-toggle="tab">Exploit Center</a></li>
                                        <li role="presentation"><a href="#dns" aria-controls="profile" role="tab" data-toggle="tab">Results</a></li>
                                        <li role="presentation"><a href="#ports" aria-controls="messages" role="tab" data-toggle="tab">Files</a></li>
                                       
                                    </ul>
                        </div>
                    </div>
                </div>
{% endblock %}

{% block content %}


</div>
{% endblock  %}

templates/scot/employees.html
{% extends 'scot/base.html' %}
{% load bootstrap4 %}
{% load staticfiles %}
{% block page_top_bar %}

<div class="top-bar clearfix">
					<div class="row gutter">
						<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
							<div class="page-title">
								<h4>{{target.name}} Employees</h4>
							</div>
						</div>
						<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
							<!-- <ul class="right-stats" id="mini-nav-right">
								<li>
									<a href="javascript:void(0)" class="btn btn-danger"><span>895</span>Sales</a>
								</li>
								<li>
									<a href="javascript:void(0)" class="btn btn-success"><span>125</span>Leads</a>
								</li>
							</ul> -->
						</div>
					</div>
				</div>
				<!-- Top bar ends -->
{% endblock %}
{% block content %}

<div class="row">
	<!-- <div class="col-md-3">
		
<div id="container" style="min-width: 310px; height: 300px; max-width: 600px; margin: 0 auto"></div>

</div> -->
<div class="col-md-12">
	<!-- <h4>Targets Monitored</h4> -->
   <a href="{% url 'employees_emails_scan' target.id %}" data-toggle="modal" class="button btn btn-info btn-sm"><span class="icon-plus4"></span> Scan For Employees </a>  <a href="{% url 'employees_emails_scan' target.id %}" class="button btn btn-info btn-sm"> Scan for Employees Emails </a>  <a href="" class="button btn btn-info btn-sm"> Scan for Employees Phone Numbers </a>
  
	
   <table id="fixedHeader" class="table table-striped  no-margin">
    <thead style="background-color: #2698e2 !important;">
		        <tr>
		            <th>Employee</th>
		            <th>Linkedin Profile Link</th>
		            <th>Email</th>
                <th>Phone Number</th>
		        </tr>
    		</thead>
    <tbody>
            {% for employee in employees %}
     
			<tr>
				<td>{{employee.name}}</td>
        <td>{{employee.linked_url}}</td>
				<td>{% for emp in employee.email_harvest_db_set.all %}
        {{emp.email_records}} <br>{% endfor %}</td>
				<td style="text-align: right;">
{% for emp in employee.phone_number.all %}
        {{emp.phone_number}} <br>{% endfor %}
        </td>
      </tr>
        
			{% endfor %}

    </tbody>
    
</table>
    
			
									</div>
								</div>
							


						

</div>
</div>
</div>
{% endblock  %}
{% block javasccript %}
<script type="text/javascript">
  $(document).on('click', '.confirm-delete', function(){
    return confirm('Are you sure you want to delete this target?');
})
</script>

{% endblock %}

templates/scot/targets (copy).html
{% extends 'scot/base.html' %}
{% load staticfiles %}
{% block page_top_bar %}

<div class="top-bar clearfix">
					<div class="row gutter">
						<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
							<div class="page-title">
								<h4>Targets</h4>
							</div>
						</div>
						<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
							<!-- <ul class="right-stats" id="mini-nav-right">
								<li>
									<a href="javascript:void(0)" class="btn btn-danger"><span>895</span>Sales</a>
								</li>
								<li>
									<a href="javascript:void(0)" class="btn btn-success"><span>125</span>Leads</a>
								</li>
							</ul> -->
						</div>
					</div>
				</div>
				<!-- Top bar ends -->
{% endblock %}
{% block content %}
<style type="text/css">
	@media (max-width: 767px) {
    .table-responsive .dropdown-menu {
        position: static !important;
    }
}
@media (min-width: 768px) {
    .table-responsive {
        overflow: inherit;
    }
}
}
tr {
   max-height: 5px !important;
   height: 5px !important;
}
</style>
<div class="row">
	<div class="col-md-5">
		<div id="container"></div>
</div>
<div class="col-md-7">
	<h4>Targets Per Country</h4>
	{% if targets %}
   <table class="table table-responsive table-hover">
    <thead style="background-color: #2698e2 !important;">
		        <tr>
		            <th>Country</th>
		            <th>Targets up</th>
		            <th>Targets down</th>
		            Total
		            <!-- <th>Country</th>
		            <th>Category</th>
		            <th>IP</th>
		            <th>Status</th>
		            <th>Action</th> -->
		        </tr>
    		</thead>
    <tbody>
        {% for target in targets %}
			<tr class="clickable" data-toggle="collapse" data-target="#{{target.id}}" aria-expanded="false" aria-controls="group-of-rows-1">
				<td>{{target.target}}</td>
				<td>{{target.name}}</td>
				<!-- <td>{{target.country}}</td>
				<td>{{target.category}}  {{target.sector}}</td>
				<td>{{target.ip}}</td>
				<td>{% if target.status == "up" %}<i class="icon-controller-record" style="color: green; font-size: 30px;"></i>{% else %}<i class="icon-controller-record" style="color: red;font-size:30px;"></i>{% endif %}</td>
				<td >
					<ul class="dropdown">
		  <button class="btn btn-sm btn-info dropdown-toggle" type="button" data-toggle="dropdown">
		  <span class="icon-lines "></span></button>
		  <ul class="dropdown-menu">
		    <li><a href="{% url 'details' target.id %}">View</a></li>
			<li><a href="{% url 'scan' target.id %}">Re-Scan</a></li>
			<li><a href="">View Vulnerabilities</a></li>
			<li><a href="">Vulnerability Re-scan</a></li>
		  </ul>
		</ul>
			</td> -->
		
        </tr>
        <tbody id="{{target.id}}" class="collapse" style="background-color: #bcdff6;">
         {% for s in target.targetspingtrack_set.all %} 
        <tr>
            <td>{{s.date}}</td>
            <td>{{s.ip}}</td>
          	<td>{{s.status}}</td>  
            
        </tr>
       {% endfor %}
    	</tbody>
			{% endfor %}
    </tbody>
    
</table>
    
			
									</div>
								</div>
							</div>
                         


							{% endif %}

</div>
</div>
{% endblock  %}
{% block javasccript %}
<style type="text/css">
	@import 'https://code.highcharts.com/css/highcharts.css';

#container {
	height: 400px;
	max-width: 800px;
	margin: 0 auto;
}

/* Link the series colors to axis colors */
.highcharts-color-0 {
	fill: #ff4d4d;
	stroke: #7cb5ec;
}
.highcharts-axis.highcharts-color-0 .highcharts-axis-line {
	stroke: #7cb5ec;
}
.highcharts-axis.highcharts-color-0 text {
	fill: #7cb5ec;
}
.highcharts-color-1 {
	fill: #90ed7d;
	stroke: #90ed7d;
}
.highcharts-axis.highcharts-color-1 .highcharts-axis-line {
	stroke: #90ed7d;
}
.highcharts-axis.highcharts-color-1 text {
	fill: #90ed7d;
}


.highcharts-yaxis .highcharts-axis-line {
	stroke-width: 2px;
}

</style>
<script src="https://code.highcharts.com/js/highcharts.js"></script>
<script src="https://code.highcharts.com/js/modules/exporting.js"></script>
<script type="text/javascript">
	Highcharts.chart('container', {

    chart: {
        type: 'column'
    },

    title: {
        text: 'Targets by Status'
    },

    yAxis: [{
        className: 'highcharts-color-0',
        title: {
            text: 'Primary axis'
        }
    }, {
        className: 'highcharts-color-1',
        opposite: true,
        title: {
            text: 'Secondary axis'
        }
    }],

    plotOptions: {
        column: {
            borderRadius: 5
        },
        series: {
            cursor: 'pointer',
            point: {
                events: {
                    click: function () {
                        location.href = 'https://en.wikipedia.org/wiki/' +
                            this.options.key;
                    }
                }
            }
        }
    },
    series: [{
        data: [{
        	y:2,
        key: 'down' }]
    }, {
        data: [{
        	y:40,
            key: 'up' } ],
       
    }]

});
</script>
{% endblock %}